### ISSUE TITLE
Keep getting `Invariant failed: You should not use <Switch> outside a <Router>`

### ISSUE THREAD

**Issue by pranaypratyush** [malj/django-parcel-ssr#3] opened 2019-06-20 11:13 UTC
Template.js
```
import Index from "black-dashboard-react/src/index.js";
export default props => {
  return (
    <Index {...props}/>
  );
}
```

Index.js
```
import React from "react";
import { createMemoryHistory } from "history";
import { Router, Route, Switch, Redirect } from "react-router-dom";

import AdminLayout from "layouts/Admin/Admin.jsx";
import RTLLayout from "layouts/RTL/RTL.jsx";

import "assets/scss/black-dashboard-react.scss";
import "assets/demo/demo.css";
import "assets/css/nucleo-icons.css";

export default () =>
  (
      <Switch>
        <Route path="/admin" render={props => <AdminLayout {...props} />}/>
        <Route path="/rtl" render={props => <RTLLayout {...props} />}/>
        <Redirect from="/" to="/admin/dashboard"/>
      </Switch>
  );
```

Difficult to debug since `console.log` doesn't work.

**Comment by pranaypratyush** [comment] 2019-06-20 11:20
Would be really nice to have a setting that quickly switches between client side and server side rendering for debugging purposes.

**Comment by malj** [comment] 2019-06-20 15:34
The error is in the title: you forgot to wrap your `<Switch>` component in`<BrowserRouter>`. Closing as the issue is not SSR related.

`console.log` in server side JavaScript code doesn't work because stdout of Node subprocesses is used for returning render results to the main Django process. However, stderr is piped as a Django template error, which is why you're seeing it.

I'll think about how to improve communication with Node workers, but as a quick workaround you can either make a custom server render script based on the default `/ssr/scripts/react/server.js` which doesn't invoke `React.createElement` during development, or simply throw an error in your code with a custom message to have it shown as a Django template error.

**Comment by pranaypratyush** [comment] 2019-06-20 16:26
My `client.js` is 
```
import React from "react";
import { BrowserRouter } from "react-router-dom";
import hydrate from "./.ssr/scripts/react/client";

export default Component => {
  const ComponentWithRouter = props => (
    <BrowserRouter>
      <Component {...props} />
    </BrowserRouter>
  );
  // console.log('client_test');
  hydrate(ComponentWithRouter);
}
```

So it should be wrapped by `<BrowserRouter>` in the end right? Made sure `client.js` is set as client script in the template options setting.

**Comment by pranaypratyush** [comment] 2019-06-20 17:30
> I'll think about how to improve communication with Node workers, but as a quick workaround you can either make a custom server render script based on the default `/ssr/scripts/react/server.js` which doesn't invoke `React.createElement` during development, or simply throw an error in your code with a custom message to have it shown as a Django template error.

Would like to help you with that although I am very new to JS but proficient with python and pipes, etc.

```
const html = ReactDOMServer.renderToString(component)

...

<div id="__react_root__" data-props="${serializedProps}">${
        process.env.NODE_ENV === 'production' ? html : ''
        }</div>`,
```
What does the above achieve?

An example script for using `connected-react-router` would be great.

**Comment by malj** [comment] 2019-06-20 19:11
Root components get rendered twice: first on the server via Node and then in the browser. The error you're getting is being thrown in the first step on the server — if it were caused by the client code you'd see it in the browser console.
Check out the React Router example: you need both custom `server.js` with `<ServerRouter>` and `client.js` with `<BrowserRouter>` because your default Component needs to be wrapped properly in both environments.

The JavaScript code you pasted is used to render the HTML string before passing it back to Django's HttpResponse. `process.env.NODE_ENV === 'production'` checks the environment and renders the initial HTML conditionally: SSR is currently disabled during development in default React scripts to prevent some cache issues with Parcel's HMR (hot module replacement) — still looking into it.

You should be able to use `connected-react-router` by combining Redux and React Router examples. You'd have to create separate history instances for browser and server environments and pass them to the Redux store creator accordingly in custom `client.js` and `server.js` scripts. Check out the connected-router SSR issue for examples: https://github.com/supasate/connected-react-router/issues/212

**Comment by pranaypratyush** [comment] 2019-06-21 10:57
Both `server.js` and `client.js` are exactly as the React Router example.

**Comment by pranaypratyush** [comment] 2019-06-21 12:32
> The JavaScript code you pasted is used to render the HTML string before passing it back to Django's HttpResponse. `process.env.NODE_ENV === 'production'` checks the environment and renders the initial HTML conditionally: SSR is currently disabled during development in default React scripts to prevent some cache issues with Parcel's HMR (hot module replacement) — still looking into it.

I don't get it. What exactly is passed as `Component` and `({ script, stylesheet},props)`?  in `server.js`

**Comment by pranaypratyush** [comment] 2019-06-21 13:12
So now my code looks like this
template.js
```
import Index from "black-dashboard-react/src/index.js";
import React from "react";

export default props => {
  return (
    <Index {...props}/>
  );
}
```
Index.js
```
import React from "react";
import { createMemoryHistory } from "history";
import { Router, Route, Switch, Redirect, BrowserRouter } from "react-router-dom";

import AdminLayout from "layouts/Admin/Admin.jsx";

import "assets/scss/black-dashboard-react.scss";
import "assets/demo/demo.css";
import "assets/css/nucleo-icons.css";


const hist = createMemoryHistory({ initialEntries: ["/"] });
export default props =>
  (
    //<Router history={hist}>
    //<BrowserRouter>
      <Switch>
        <Route path="/admin" render={props => <AdminLayout {...props} />}/>
        <Redirect from="/" to="/admin/dashboard"/>
      </Switch>
    //</BrowserRouter>
    //</Router>
  );
```
And this works but only for path `/` and gives a `ReferenceError: document is not defined` otherwise. Suspect something related to props.

**Comment by malj** [comment] 2019-06-22 14:43
Please upload an example project with the same setup to GitHub so I can check the whole codebase, as I've had no problems creating a new project using the React Router example. 

 > I don't get it. What exactly is passed as `Component` and `({ script, stylesheet},props)`? in `server.js`

`server.js` and `client.js` functions wrap your default exports for Node and browser environments respectively. The arguments for the server side function represent the following: 

- `Component` represents a default export in your `bundles/` dirs, i.e. the root component
- `script` and `stylesheet` are string paths to bundle's `.js` and `.css` files generated by Parcel
- `props` is an optional context object from Django views

The default wrapper functions are provided for React, but the idea is that you can always write a custom pair if you need extra features such as routing in your case, or if you want to use a different view library instead of React.

**Comment by malj** [comment] 2019-10-10 12:55
Closing for inactivity.

**Closed as completed by malj** 2019-10-10 12:55 UTC
